-- PG stored procedure template for inserted or uppdated action

create or replace FUNCTION dwd_dim_material_merge(
  new_chinese_name text, 
  new_material_code text, 
  new_old_code text, 
  new_english_name text, 
  new_profit_center text, 
  new_gtin text, 
  new_sap_upl_level1_code text, 
  new_sap_upl_level1_name text, 
  new_sap_upl_level2_code text, 
  new_sap_upl_level2_name text, 
  new_sap_upl_level3_code text, 
  new_sap_upl_level3_name text, 
  new_sap_upl_level4_code text, 
  new_sap_upl_level4_name text, 
  new_sap_upl_level5_code text, 
  new_sap_upl_level5_name text, 
  new_special_procurement text, 
  new_latest_cfda text, 
  new_sheets text, 
  new_mmpp text, 
  new_d_chain text, 
  new_spk text, 
  new_default_location text, 
  new_source_list_indicator text, 
  new_pdt text, 
  new_grt text, 
  new_qi_flag text, 
  new_loading_group text, 
  new_legal_status text, 
  new_delivery_plant text, 
  new_shelf_life_sap text, 
  new_standard_cost float8, 
  new_transfer_price float8, 
  new_pra text, 
  new_material_type text, 
  new_pra_valid_from text, 
  new_pra_valid_to text, 
  new_pra_status text, 
  new_pra_release_status_code text, 
  new_standard_cost_usd float8, 
  new_abc_class text, 
  new_division_id text , 
  new_division_display_name text , 
  new_product_line1_code text, 
  new_product_line1_name text, 
  new_product_line2_code text, 
  new_product_line2_name text, 
  new_product_line3_code text, 
  new_product_line3_name text, 
  new_product_line4_code text, 
  new_product_line4_name text, 
  new_product_line5_code text, 
  new_product_line5_name text, 
  new_m_shelf_life_for_oboselete text, 
  new_xyz text, 
  new_m_isv_bp text, 
  new_product_model text, 
  new_business_group text, 
  new_sub_division text, 
  new_mit text, 
  new_dlr_quota_product_line_id integer, 
  new_dlr_quota_product_line text, 
  new_dlr_auth_productline_id integer, 
  new_dlr_auth_productline text, 
  new_sales_status text, 
  new_is_active_for_sale integer, 
  new_subbu_code text, 
  new_subbu_name text, 
  new_lp_subbu_code text, 
  new_lp_subbu_name text, 
  new_sub_division_bak text,
  new_dt date)
RETURNS VOID AS
$$

BEGIN
    
    LOOP
        -- first try to update the key
        -- not there, so try to insert the key
        -- if someone else inserts the same key concurrently,
        -- we could get a unique-key failure
        BEGIN
            INSERT INTO dwd_dim_material(chinese_name, material_code, old_code, english_name, profit_center, gtin, sap_upl_level1_code, sap_upl_level1_name, sap_upl_level2_code, sap_upl_level2_name, sap_upl_level3_code, sap_upl_level3_name, sap_upl_level4_code, sap_upl_level4_name, sap_upl_level5_code, sap_upl_level5_name, special_procurement, latest_cfda, sheets, mmpp, d_chain, spk, default_location, source_list_indicator, pdt, grt, qi_flag, loading_group, legal_status, delivery_plant, shelf_life_sap, standard_cost, transfer_price, pra, material_type, pra_valid_from, pra_valid_to, pra_status, pra_release_status_code, standard_cost_usd, abc_class, division_id, division_display_name, product_line1_code, product_line1_name, product_line2_code, product_line2_name, product_line3_code, product_line3_name, product_line4_code, product_line4_name, product_line5_code, product_line5_name, m_shelf_life_for_oboselete, xyz, m_isv_bp, product_model, business_group, sub_division, mit, dlr_quota_product_line_id, dlr_quota_product_line, dlr_auth_productline_id, dlr_auth_productline, sales_status, is_active_for_sale, subbu_code, subbu_name, lp_subbu_code, lp_subbu_name, sub_division_bak, dt)
             VALUES (  new_chinese_name , 
                        new_material_code , 
                        new_old_code , 
                        new_english_name , 
                        new_profit_center , 
                        new_gtin , 
                        new_sap_upl_level1_code , 
                        new_sap_upl_level1_name , 
                        new_sap_upl_level2_code , 
                        new_sap_upl_level2_name , 
                        new_sap_upl_level3_code , 
                        new_sap_upl_level3_name , 
                        new_sap_upl_level4_code , 
                        new_sap_upl_level4_name , 
                        new_sap_upl_level5_code , 
                        new_sap_upl_level5_name , 
                        new_special_procurement , 
                        new_latest_cfda , 
                        new_sheets , 
                        new_mmpp , 
                        new_d_chain , 
                        new_spk , 
                        new_default_location , 
                        new_source_list_indicator , 
                        new_pdt , 
                        new_grt , 
                        new_qi_flag , 
                        new_loading_group , 
                        new_legal_status , 
                        new_delivery_plant , 
                        new_shelf_life_sap , 
                        new_standard_cost , 
                        new_transfer_price , 
                        new_pra , 
                        new_material_type , 
                        new_pra_valid_from , 
                        new_pra_valid_to , 
                        new_pra_status , 
                        new_pra_release_status_code , 
                        new_standard_cost_usd , 
                        new_abc_class , 
                        new_division_id  , 
                        new_division_display_name  , 
                        new_product_line1_code , 
                        new_product_line1_name , 
                        new_product_line2_code , 
                        new_product_line2_name , 
                        new_product_line3_code , 
                        new_product_line3_name , 
                        new_product_line4_code , 
                        new_product_line4_name , 
                        new_product_line5_code , 
                        new_product_line5_name , 
                        new_m_shelf_life_for_oboselete , 
                        new_xyz , 
                        new_m_isv_bp , 
                        new_product_model , 
                        new_business_group , 
                        new_sub_division , 
                        new_mit , 
                        new_dlr_quota_product_line_id , 
                        new_dlr_quota_product_line , 
                        new_dlr_auth_productline_id , 
                        new_dlr_auth_productline , 
                        new_sales_status , 
                        new_is_active_for_sale , 
                        new_subbu_code , 
                        new_subbu_name , 
                        new_lp_subbu_code , 
                        new_lp_subbu_name , 
                        new_sub_division_bak ,
                        new_dt );
            RETURN;
        EXCEPTION WHEN unique_violation THEN
            -- Do nothing, and loop to try the UPDATE again.
        END;
    END LOOP;
END;
$$
LANGUAGE plpgsql;