-- PG stored procedure template for inserted or uppdated action

create or replace FUNCTION dws_iekpi_e2e_merge(
	new_outbound_yr text ,
	new_pickupdocument_no text ,
	new_commericalinvoice text ,
	new_inbound_invoice text ,
	new_emergencysigns text ,
	new_forwarding text ,
	new_arrivalgoods_type text ,
	new_shipfrom_country text ,
	new_preinspection_flag text ,
	new_bscinformslcdate text ,
	new_t1pickupdate text ,
	new_etd text ,
	new_eta text ,
	new_reviseetd text ,
	new_reviseeta text ,
	new_actualarrivaltime text ,
	new_forwordinginformslcpick text ,
	new_dockwarrantdate text ,
	new_intoinventorydate text ,
	new_inbounddeclaration_startdate text ,
	new_inbounddeclaration_finishdate text ,
	new_picturetaken_date text ,
	new_inspection_appointmentdate text ,
	new_inspection_finishdate text ,
	new_inbound_pics text ,
	new_inbound_mon text ,
	new_inbound_yr text ,
	new_outbound_biz_no text ,
	new_declaration_itemname text ,
	new_outbound_commericalinvoice text ,
	new_outbound_invoice text ,
	new_document_finishpreparationdate text ,
	new_customrelease_1 text ,
	new_commodityinspection_date text ,
	new_chineselabelpicturereceiveddate text ,
	new_customrelease_2 text ,
	new_testscheduled_date text ,
	new_actualtest_date text ,
	new_ciq_signcompletiondate text ,
	new_taxpayment_applicationdate text ,
	new_taxpayment_completiondate text ,
	new_declaration_completiondate text ,
	new_is_excluded text ,
	new_is_malaysia text ,
	new_abnormal_reason text ,
	new_status text ,
	new_is_valid text ,
	new_category_code text ,
	new_distribution_status text ,
	new_outbound_pieces text ,
	new_destination_wh text ,
	new_airport text ,
	new_outbound_mon text ,
	new_dock_invent_cd text ,
	new_dock_invent_holiday text ,
	new_dock_invent_wd text ,
	new_invent_cust1_cd text ,
	new_invent_cust1_holiday text ,
	new_invent_cust1_wd text ,
	new_cust1_chinesepicture_cd text ,
	new_cust1_chinesepicture_holiday text ,
	new_cust1_chinesepicture_wd text ,
	new_chinesepicture_commodity_cd text ,
	new_chinesepicture_commodity_holiday text ,
	new_chinesepicture_commodity_wd text ,
	new_commod_act_cust2_cd text ,
	new_commod_act_cust2_holiday text ,
	new_commod_act_cust2_wd text ,
	new_act_ciq_cd text ,
	new_act_ciq_holiday text ,
	new_act_ciq_wd text ,
	new_start_end_cd numeric(18,2),
	new_start_end_holiday numeric(18,2),
	new_start_end_wd numeric(18,2),
	new_coodraft_receiveddate text,
	new_coocertificate_receiveddate text,
	new_jsons text
)
RETURNS VOID AS
$$
BEGIN
    LOOP
        -- first try to update the key
        -- not there, so try to insert the key
        -- if someone else inserts the same key concurrently,
        -- we could get a unique-key failure
        BEGIN
            INSERT INTO dws_iekpi_e2e(  outbound_yr,pickupdocument_no, commericalinvoice, inbound_invoice, emergencysigns, forwarding, arrivalgoods_type, shipfrom_country, preinspection_flag, bscinformslcdate, t1pickupdate, etd, eta, reviseetd, reviseeta, actualarrivaltime, forwordinginformslcpick, dockwarrantdate, intoinventorydate, inbounddeclaration_startdate, inbounddeclaration_finishdate, picturetaken_date, inspection_appointmentdate, inspection_finishdate, inbound_pics, inbound_mon, inbound_yr, outbound_biz_no, declaration_itemname, outbound_commericalinvoice, outbound_invoice, document_finishpreparationdate, customrelease_1, commodityinspection_date, chineselabelpicturereceiveddate, customrelease_2, testscheduled_date, actualtest_date, ciq_signcompletiondate, taxpayment_applicationdate, taxpayment_completiondate, declaration_completiondate, is_excluded, is_malaysia, abnormal_reason, status, is_valid, category_code, distribution_status, outbound_pieces, destination_wh, airport, outbound_mon, dock_invent_cd, dock_invent_holiday, dock_invent_wd, invent_cust1_cd, invent_cust1_holiday, invent_cust1_wd, cust1_chinesepicture_cd, cust1_chinesepicture_holiday, cust1_chinesepicture_wd, chinesepicture_commodity_cd, chinesepicture_commodity_holiday, chinesepicture_commodity_wd, commod_act_cust2_cd, commod_act_cust2_holiday, commod_act_cust2_wd, act_ciq_cd, act_ciq_holiday, act_ciq_wd,start_end_cd,start_end_holiday,start_end_wd,coodraft_receiveddate,coocertificate_receiveddate,jsons
) VALUES (
	new_outbound_yr ,
                    	new_pickupdocument_no  ,
	new_commericalinvoice  ,
	new_inbound_invoice  ,
	new_emergencysigns  ,
	new_forwarding  ,
	new_arrivalgoods_type  ,
	new_shipfrom_country  ,
	new_preinspection_flag  ,
	new_bscinformslcdate  ,
	new_t1pickupdate  ,
	new_etd  ,
	new_eta  ,
	new_reviseetd  ,
	new_reviseeta  ,
	new_actualarrivaltime  ,
	new_forwordinginformslcpick  ,
	new_dockwarrantdate  ,
	new_intoinventorydate  ,
	new_inbounddeclaration_startdate  ,
	new_inbounddeclaration_finishdate  ,
	new_picturetaken_date  ,
	new_inspection_appointmentdate  ,
	new_inspection_finishdate  ,
	new_inbound_pics  ,
	new_inbound_mon  ,
	new_inbound_yr  ,
	new_outbound_biz_no  ,
	new_declaration_itemname  ,
	new_outbound_commericalinvoice  ,
	new_outbound_invoice  ,
	new_document_finishpreparationdate  ,
	new_customrelease_1  ,
	new_commodityinspection_date  ,
	new_chineselabelpicturereceiveddate  ,
	new_customrelease_2  ,
	new_testscheduled_date  ,
	new_actualtest_date  ,
	new_ciq_signcompletiondate  ,
	new_taxpayment_applicationdate  ,
	new_taxpayment_completiondate  ,
	new_declaration_completiondate  ,
	new_is_excluded  ,
	new_is_malaysia  ,
	new_abnormal_reason  ,
	new_status  ,
	new_is_valid  ,
	new_category_code  ,
	new_distribution_status  ,
	new_outbound_pieces  ,
	new_destination_wh  ,
	new_airport  ,
	new_outbound_mon  ,
	new_dock_invent_cd  ,
	new_dock_invent_holiday  ,
	new_dock_invent_wd  ,
	new_invent_cust1_cd  ,
	new_invent_cust1_holiday  ,
	new_invent_cust1_wd  ,
	new_cust1_chinesepicture_cd  ,
	new_cust1_chinesepicture_holiday  ,
	new_cust1_chinesepicture_wd  ,
	new_chinesepicture_commodity_cd  ,
	new_chinesepicture_commodity_holiday  ,
	new_chinesepicture_commodity_wd  ,
	new_commod_act_cust2_cd  ,
	new_commod_act_cust2_holiday  ,
	new_commod_act_cust2_wd  ,
	new_act_ciq_cd  ,
	new_act_ciq_holiday  ,
	new_act_ciq_wd  ,
	new_start_end_cd ,
	new_start_end_holiday ,
	new_start_end_wd ,
	new_coodraft_receiveddate,
	new_coocertificate_receiveddate,
	new_jsons
                );
            RETURN;
        EXCEPTION WHEN unique_violation THEN
            -- Do nothing, and loop to try the UPDATE again.
        END;
    END LOOP;
END;
$$
LANGUAGE plpgsql;